{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "04599e46-eb7e-4721-9c48-37a8f1cc1cfe",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: python-edgar in /Users/drod/opt/anaconda3/lib/python3.9/site-packages (3.1.3)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install python-edgar"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "id": "1965fb69-e5ae-438d-a2e8-c4569ae9904a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Import packages\n",
    "import edgar\n",
    "import pandas as pd\n",
    "import requests\n",
    "import json"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e4f93d27-32eb-4aa2-8361-38780c21a5be",
   "metadata": {},
   "source": [
    "### Downlaod Master Indices"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "id": "b0da8a1c-477c-4c08-97b7-acd1948b13b5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Download master indices from SEC\n",
    "user_agent = \"DRod/1.0 (dr1902@nyu.edu; For educational purposes)\"\n",
    "edgar.download_index('.', 2022, user_agent, skip_all_present_except_last=False)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a70bcae2-8250-46fa-86e9-c2e750a71e2d",
   "metadata": {},
   "source": [
    "### Retrieve the latest S&P500 composition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "6e5888db-7ef6-4d7a-b851-07542d1a5990",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load historical sp500 composition\n",
    "sp500_com = pd.read_excel('sp500_composition.xlsx')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "id": "7def5371-6e7a-4b0e-85db-1011e3bc5bd5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Present year\n",
    "today = pd.to_datetime('today').year\n",
    "\n",
    "# Retrieve the sp500 composition from the previous quarter\n",
    "def update_indices(year, quarter, form):\n",
    "    # Assign timestamps for different quarters\n",
    "    if quarter == 1:\n",
    "        date = pd.Timestamp(year, 1, 1)\n",
    "    elif quarter == 2:\n",
    "        date = pd.Timestamp(year, 4, 1)\n",
    "    elif quarter == 3:\n",
    "        date = pd.Timestamp(year, 7, 1)\n",
    "    else:\n",
    "        date = pd.Timestamp(year, 10, 1)\n",
    "\n",
    "    # Find the closest date to the assigned dates to the quarters\n",
    "    closest_date = find_close_date(date)\n",
    "\n",
    "    # Export company names of S&P500 based on the closest date\n",
    "    if form == 'name':\n",
    "        companies = sp500_com.loc[sp500_com.Date==closest_date, 'Company Name']\n",
    "        lst = []\n",
    "        for company in companies:\n",
    "            lst.append(company.strip())\n",
    "        return lst\n",
    "    # Export tickers of S&P500 based on the closest date\n",
    "    elif form == 'ticker':\n",
    "        tickers = sp500_com.loc[sp500_com.Date==closest_date, 'Ticker']\n",
    "        lst = []\n",
    "        for ticker in tickers:\n",
    "            lst.append(ticker.strip())\n",
    "        return lst\n",
    "\n",
    "\n",
    "# Find the closest date to the assigned dates to the quarters\n",
    "def find_close_date(date):\n",
    "    \n",
    "    close_date = pd.Timestamp(2000, 1, 1)\n",
    "    time_delta = date - close_date\n",
    "    \n",
    "    for row in sp500_com.iterrows():\n",
    "        if row[1][0] <= date and date - row[1][0] < time_delta:\n",
    "            close_date = row[1][0]\n",
    "            time_delta = date - close_date\n",
    "    return close_date"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "id": "cd72ef3c-312e-439d-8dbd-bd52c5889b63",
   "metadata": {},
   "outputs": [],
   "source": [
    "# URL to the SEC's CIK-to-Ticker mapping file\n",
    "url = \"https://www.sec.gov/files/company_tickers.json\"\n",
    "headers = {'User-Agent':\"DRod/1.0 (dr1902@nyu.edu; For educational purposes)\"}\n",
    "\n",
    "# Download the file\n",
    "response = requests.get(url, headers=headers)\n",
    "data = response.json()\n",
    "\n",
    "# Function to get ticker from CIK\n",
    "def get_ticker_from_cik(cik):\n",
    "    for company in data.values():\n",
    "        if company['cik_str'] == cik:\n",
    "            return company['ticker']\n",
    "    return None"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 77,
   "id": "bd772d14-3790-4753-b136-1b23783030e5",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  if row[1][0] <= date and date - row[1][0] < time_delta:\n",
      "/var/folders/60/75vh_thj2m57nynzg5tgw0300000gn/T/ipykernel_96250/2795958831.py:43: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`\n",
      "  close_date = row[1][0]\n"
     ]
    }
   ],
   "source": [
    "prefix = 'https://www.sec.gov/Archives/'\n",
    "company_name = []\n",
    "time = []\n",
    "file = []\n",
    "link = []\n",
    "\n",
    "for year in range(2022, today+1):\n",
    "    \n",
    "    # There's been only 3 quarters so far in 2024\n",
    "    if year==today:\n",
    "        quarters = 4\n",
    "    else:\n",
    "        quarters = 5\n",
    "    \n",
    "    for quarter in range(1, quarters):\n",
    "        \n",
    "        # Loading master index\n",
    "        filename = str(year)+'-QTR'+str(quarter)+'.tsv'\n",
    "        mas_ind = pd.read_csv(filename, sep='|', header=None)\n",
    "        \n",
    "        # Retrieving tickers using the updated(latest) sp500 composition\n",
    "        sp_tlst = update_indices(year, quarter, 'ticker')\n",
    "        \n",
    "        # Checking every file entry\n",
    "        for i in range(len(mas_ind.loc[:, 0])):\n",
    "\n",
    "            # Getting tickers using cik from master index\n",
    "            cik = int(mas_ind.loc[i, 0])\n",
    "            ticker = get_ticker_from_cik(cik)\n",
    "\n",
    "            # Checking if the ticker is in sp500\n",
    "            if ticker in sp_tlst:\n",
    "                # Checking if the file is 10K or 10Q\n",
    "                if mas_ind.loc[i, 2] == '10-K' or mas_ind.loc[i, 2]=='10-K/A' or mas_ind.loc[i, 2]=='10-Q' or mas_ind.loc[i, 2]=='10-Q/A':\n",
    "                    company_name.append(mas_ind.loc[i, 1])\n",
    "                    time.append(str(year)+'Q'+str(quarter))\n",
    "                    file.append(mas_ind.loc[i, 2])\n",
    "                    url = prefix+mas_ind.loc[i, 5]\n",
    "                    link.append(url)\n",
    "                else:\n",
    "                    continue\n",
    "            else:\n",
    "                continue"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 78,
   "id": "1ffd655c-2735-4319-9e79-75b736731a9a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>company_name</th>\n",
       "      <th>published_time</th>\n",
       "      <th>type</th>\n",
       "      <th>link_url</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>HENRY SCHEIN INC</td>\n",
       "      <td>2022Q1</td>\n",
       "      <td>10-K</td>\n",
       "      <td>https://www.sec.gov/Archives/edgar/data/100022...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>WATERS CORP /DE/</td>\n",
       "      <td>2022Q1</td>\n",
       "      <td>10-K</td>\n",
       "      <td>https://www.sec.gov/Archives/edgar/data/100069...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>ESTEE LAUDER COMPANIES INC</td>\n",
       "      <td>2022Q1</td>\n",
       "      <td>10-Q</td>\n",
       "      <td>https://www.sec.gov/Archives/edgar/data/100125...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>NetApp, Inc.</td>\n",
       "      <td>2022Q1</td>\n",
       "      <td>10-Q</td>\n",
       "      <td>https://www.sec.gov/Archives/edgar/data/100204...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>AMEREN CORP</td>\n",
       "      <td>2022Q1</td>\n",
       "      <td>10-K</td>\n",
       "      <td>https://www.sec.gov/Archives/edgar/data/100291...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5351</th>\n",
       "      <td>SYSCO CORP</td>\n",
       "      <td>2024Q3</td>\n",
       "      <td>10-K</td>\n",
       "      <td>https://www.sec.gov/Archives/edgar/data/96021/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5352</th>\n",
       "      <td>TELEFLEX INC</td>\n",
       "      <td>2024Q3</td>\n",
       "      <td>10-Q</td>\n",
       "      <td>https://www.sec.gov/Archives/edgar/data/96943/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5353</th>\n",
       "      <td>TERADYNE, INC</td>\n",
       "      <td>2024Q3</td>\n",
       "      <td>10-Q</td>\n",
       "      <td>https://www.sec.gov/Archives/edgar/data/97210/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5354</th>\n",
       "      <td>TEXAS INSTRUMENTS INC</td>\n",
       "      <td>2024Q3</td>\n",
       "      <td>10-Q</td>\n",
       "      <td>https://www.sec.gov/Archives/edgar/data/97476/...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5355</th>\n",
       "      <td>THERMO FISHER SCIENTIFIC INC.</td>\n",
       "      <td>2024Q3</td>\n",
       "      <td>10-Q</td>\n",
       "      <td>https://www.sec.gov/Archives/edgar/data/97745/...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5356 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                       company_name published_time  type  \\\n",
       "0                  HENRY SCHEIN INC         2022Q1  10-K   \n",
       "1                  WATERS CORP /DE/         2022Q1  10-K   \n",
       "2        ESTEE LAUDER COMPANIES INC         2022Q1  10-Q   \n",
       "3                      NetApp, Inc.         2022Q1  10-Q   \n",
       "4                       AMEREN CORP         2022Q1  10-K   \n",
       "...                             ...            ...   ...   \n",
       "5351                     SYSCO CORP         2024Q3  10-K   \n",
       "5352                   TELEFLEX INC         2024Q3  10-Q   \n",
       "5353                  TERADYNE, INC         2024Q3  10-Q   \n",
       "5354          TEXAS INSTRUMENTS INC         2024Q3  10-Q   \n",
       "5355  THERMO FISHER SCIENTIFIC INC.         2024Q3  10-Q   \n",
       "\n",
       "                                               link_url  \n",
       "0     https://www.sec.gov/Archives/edgar/data/100022...  \n",
       "1     https://www.sec.gov/Archives/edgar/data/100069...  \n",
       "2     https://www.sec.gov/Archives/edgar/data/100125...  \n",
       "3     https://www.sec.gov/Archives/edgar/data/100204...  \n",
       "4     https://www.sec.gov/Archives/edgar/data/100291...  \n",
       "...                                                 ...  \n",
       "5351  https://www.sec.gov/Archives/edgar/data/96021/...  \n",
       "5352  https://www.sec.gov/Archives/edgar/data/96943/...  \n",
       "5353  https://www.sec.gov/Archives/edgar/data/97210/...  \n",
       "5354  https://www.sec.gov/Archives/edgar/data/97476/...  \n",
       "5355  https://www.sec.gov/Archives/edgar/data/97745/...  \n",
       "\n",
       "[5356 rows x 4 columns]"
      ]
     },
     "execution_count": 78,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "file_dict = {'company_name': company_name, 'published_time': time, 'type': file, 'link_url': link}\n",
    "df = pd.DataFrame(file_dict)\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 79,
   "id": "bdcf8da5-71f9-469f-8e4f-83d85749aa76",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.to_csv('sp500_files.csv', index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2a3ae75a-39d8-4ac5-b841-8723d469ee87",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
